name: ClipStrip
options:
  minimumXcodeGenVersion: 2.44.0
settings:
  base:
    SWIFT_VERSION: 5.10
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 1
    CODE_SIGN_STYLE: Automatic
    MACOSX_DEPLOYMENT_TARGET: 13.0
targets:
  ClipStrip:
    type: application
    platform: macOS
    sources:
      - path: ClipStripApp
    info:
      path: ClipStripApp/Info.plist
    entitlements:
      path: ClipStripApp/ClipStrip.entitlements
    settings:
      base:
        PRODUCT_NAME: ClipStrip
        PRODUCT_BUNDLE_IDENTIFIER: com.spider82productions.clipstrip
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_HARDENED_RUNTIME: YES
        DEVELOPMENT_TEAM: ""
